version: '3.8'

services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./sys-stats/build:/var/www/frontend
      - ./nginx/nginx_prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - smartcow_network
    depends_on:
      - api
      - frontend
  
  frontend:
    image: silambu18/frontend
    build:
      context: ./sys-stats/
      dockerfile: Dockerfile
    container_name: frontend
    command: ./entrypoint.sh
    volumes:
      - ./sys-stats:/usr/frontend
    networks:
      smartcow_network:
        aliases:
          - frontend
    # expose:
    #   - 3000
    ports:
      - "3000:3000"

  api:
    image: silambu18/api
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: api
    command: ./entrypoint.sh
    volumes:
      - ./api:/var/www/api
    expose:
      - 5000
    networks:
      smartcow_network:
        aliases:
          - api

networks:
  smartcow_network: