version: '3.8'

services:

  frontend:
    image: frontend
    build:
      context: ./sys-stats/
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    image: api
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: api
    command: ./entrypoint.sh
    volumes:
      - ./api:/var/www/api
    ports:
      - "5000:5000"
    # networks:
    #   smartcow_network:
    #     aliases:
    #       - api

  # nginx:
  #   image: nginx:1.15
  #   container_name: nginx
  #   restart: unless-stopped
  #   volumes:
  #     - ./:/var/www/frontend
  #     - ./nginx/nginx_prod.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - 80:80
  #   networks:
  #     - smartcow_network
  #   depends_on:
  #     - api
  #     - frontend

# networks:
#   smartcow_network:


