apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  # namespace: reactapp
  labels:
    app: api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-app
          image: silambu18/api:latest
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: api
  # namespace : reactapp
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30202
      
  
